<a href="https://colab.research.google.com/github/Ranjitghadge/Python-Practice/blob/main/Daily_Practice_Python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
A =  'Ranjit is Data Scientist'


In [ ]:
print(A[0])

R


In [ ]:
print(A[-1])

t


In [ ]:
print(A[5:0:-1])

tijna


In [ ]:
print(A[::-1])

tsitneicS ataD si tijnaR


In [ ]:
A[0] = 'A'

TypeError: ignored

In [ ]:
b = 'ranjit'
c = 'ghadge'

print(b+c)

ranjitghadge


In [ ]:
print(A.capitalize())

Ranjit is data scientist


In [ ]:
A.title()

'Ranjit Is Data Scientist'

In [ ]:
A.upper()

'RANJIT IS DATA SCIENTIST'

In [ ]:
A.swapcase()

'rANJIT IS dATA sCIENTIST'

In [ ]:
A.count('R')

1

In [ ]:
A.find('R')

0

In [ ]:
A.split('R')

['', 'anjit is Data Scientist']

In [ ]:
''.join([b,c])

'ranjitghadge'

In [ ]:
import pandas as pd

data = {
    'Transaction_ID': [1001, 1002, 1003, 1004, 1005, 1006],
    'Product': ['A', 'B', 'A', 'C', 'B', 'C'],
    'Quantity': [10, 15, 20, 12, 8, 10],
    'Price': [5.00, 7.50, 6.00, 8.25, 6.50, 9.00]
}

df = pd.DataFrame(data)

In [ ]:
df

Transaction_ID Product  Quantity  Price
0            1001       A        10   5.00
1            1002       B        15   7.50
2            1003       A        20   6.00
3            1004       C        12   8.25
4            1005       B         8   6.50
5            1006       C        10   9.00

In [ ]:
df[df['Product'] == 'A']['Quantity'].sum()

30

In [ ]:
df[df['Product'] == 'B']['Price'].mean()

7.0

Question 3:
What is the maximum quantity sold among all products?

In [ ]:
df['Quantity'].max()

20

Question 4:
What is the total revenue generated from all transactions?

In [ ]:
A = df['Quantity'] * df['Price']
A.sum()


523.5

Question 5:
What is the minimum price among all products?

In [ ]:
df['Price'].min()

5.0

Question 6:
How many unique products are there in the dataset?

In [ ]:
df.groupby('Product').count().shape[0]

3

Question 7:
What is the average quantity sold for product 'C'?

In [ ]:
df[df['Product'] == 'C']['Quantity'].mean()

11.0

Question 8:
What is the total quantity sold for each product?

In [ ]:
df.groupby('Product')['Quantity'].sum()

Product
A    30
B    23
C    22
Name: Quantity, dtype: int64

Question 9:
What is the average price per unit for each product?

In [ ]:
df.groupby('Product')['Price'].mean()

Product
A    5.500
B    7.000
C    8.625
Name: Price, dtype: float64

Question 10:
What is the total revenue generated from each transaction (product-wise) in descending order?

In [ ]:
df['revenue'] = df['Quantity'] * df['Price']
df.sort_values('revenue',ascending = False)

#df.groupby('Product')[df['Quantity'] * df['Price']].sum()

#A = df['Quantity'] * df['Price']


Transaction_ID Product  Quantity  Price  revenue
2            1003       A        20   6.00    120.0
1            1002       B        15   7.50    112.5
3            1004       C        12   8.25     99.0
5            1006       C        10   9.00     90.0
4            1005       B         8   6.50     52.0
0            1001       A        10   5.00     50.0

In [ ]:
transaction_revenue = df.groupby('Transaction_ID')['Quantity', 'Price'].sum()
transaction_revenue['Revenue'] = transaction_revenue['Quantity'] * transaction_revenue['Price']
sorted_revenue = transaction_revenue.sort_values('Revenue', ascending=False)
sorted_revenue


<ipython-input-66-df7306d4631f>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  transaction_revenue = df.groupby('Transaction_ID')['Quantity', 'Price'].sum()


Quantity  Price  Revenue
Transaction_ID                          
1003                  20   6.00    120.0
1002                  15   7.50    112.5
1004                  12   8.25     99.0
1006                  10   9.00     90.0
1005                   8   6.50     52.0
1001                  10   5.00     50.0

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Mary', 'Alex', 'Mark', 'Jane'],
    'Subject': ['Math', 'Science', 'Math', 'Science', 'Math'],
    'Score': [85, 92, 78, 88, 90]
}

df = pd.DataFrame(data)

In [ ]:
df

Name  Subject  Score
0  John     Math     85
1  Mary  Science     92
2  Alex     Math     78
3  Mark  Science     88
4  Jane     Math     90

In [ ]:
df.groupby('Subject')['Score'].mean()

Subject
Math       84.333333
Science    90.000000
Name: Score, dtype: float64

In [ ]:
import pandas as pd

data = {
    'Name': ['John', 'Mary', 'Alex', 'Mark', 'Jane'],
    'Age': [25, 30, 28, 35, 27],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [5000, 6000, 5500, 4500, 6500]
}

df = pd.DataFrame(data)


In [ ]:
df

Name  Age      City  Salary
0  John   25  New York    5000
1  Mary   30    London    6000
2  Alex   28     Paris    5500
3  Mark   35     Tokyo    4500
4  Jane   27    Sydney    6500

In [ ]:
df['Salary'].mean()

5500.0

In [ ]:
df['Age'].max()

35

In [ ]:
df.groupby('City').count()

Name  Age  Salary
City                       
London       1    1       1
New York     1    1       1
Paris        1    1       1
Sydney       1    1       1
Tokyo        1    1       1

In [ ]:
df['Salary'].sum()

27500

In [ ]:
df[df['Salary'] == df['Salary'].max()]

Name  Age    City  Salary
4  Jane   27  Sydney    6500

In [ ]:
df.groupby('Age').mean()

<ipython-input-91-16c96bc1028d>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Age').mean()


Salary
Age        
25   5000.0
27   6500.0
28   5500.0
30   6000.0
35   4500.0

In [ ]:
import pandas as pd

data = {
    'Transaction_ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Product': ['A', 'B', 'A', 'C', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Quantity': [10, 5, 3, 8, 12, 7, 4, 9, 6, 11],
    'Price': [10.00, 15.00, 12.50, 8.00, 11.50, 9.75, 14.00, 10.50, 13.25, 9.00]
}

df = pd.DataFrame(data)

df

Transaction_ID Product  Quantity  Price
0               1       A        10  10.00
1               2       B         5  15.00
2               3       A         3  12.50
3               4       C         8   8.00
4               5       B        12  11.50
5               6       C         7   9.75
6               7       A         4  14.00
7               8       B         9  10.50
8               9       C         6  13.25
9              10       A        11   9.00

Question 1:
What is the total revenue generated from each transaction (product-wise) in descending order?

In [ ]:

df.groupby('Product')['Quantity'].sum()

Product
A    28
B    26
C    21
Name: Quantity, dtype: int64

Question 2:
What is the total quantity sold for each product?

In [ ]:
df.groupby('Product')['revenue'].mean()

Product
A     73.125000
B    102.500000
C     70.583333
Name: revenue, dtype: float64

In [ ]:
df['revenue'].max()

138.0

In [ ]:
students = {
    'Marks':[20,56,15],
    'Name':['Ranjit','Ghadge','Rupesh']}

student= pd.DataFrame(students)
student.set_index('Name',inplace = True)
student

Marks
Name         
Ranjit     20
Ghadge     56
Rupesh     15

In [2]:
n1 = input()
n2 = input()

n1,n2 = n2,n1

print(n1)
print(n2)

5
10
10
5


In [8]:
def factorial(n):
  fact = 1
  for i in range(1,n+1):
    fact = fact * i
  return fact

print(factorial(5))


120


In [11]:
n1 = 0
n2 = 1
num = int(input())
for i in range(2,num):
  sum = n1 + n2
  print(sum)
  n1 = n2
  n2 = sum

10
1
2
3
5
8
13
21
34


In [18]:
num = int(input())
n1 = 0
n2 = 1
print(n1)
print(n2)
for i in range(2,num):
  sum=n1+n2
  print(sum)
  n1=n2
  n2=sum





10
0
1
1
2
3
5
8
13
21
34


In [21]:
num = int(input())
if num % 2 ==0:
  print('even no')
else:
  print('odd no')

7
odd no


In [27]:
num = int(input())

if num == 1:
  print('no is not prime')
if num >1:
    for i in range(2,num):
      if num % i == 0:
        print('No is not prime')
        break
    else:
        print('no is prime')

13
no is prime


In [28]:
5/2

2.5

In [29]:
5%2

1

In [30]:
5//2

2

In [31]:
import numpy as np

In [32]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [33]:
b = np.array([5,2,4,5,1,6,4,5])
print(b)

[5 2 4 5 1 6 4 5]


In [35]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [42]:
a1 = np.arange(8).reshape(2,4)
a1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [44]:
a1.ndim

2

In [46]:
a1.shape

(2, 4)

In [47]:
a1.size

8

In [50]:
a2 = np.arange(12).reshape(3,4)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [54]:
a3 = np.random.random((3,3))*100
a3

array([[28.4041272 , 87.76643403, 19.08465582],
       [28.27255892, 61.45029194,  4.79955686],
       [74.80909478, 27.67657238, 95.73615723]])