<a href="https://colab.research.google.com/github/Ranjitghadge/Python-Practice/blob/main/Python_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Basic

In [ ]:
type(5.1)

float

In [ ]:
int(5.1245)

5

In [ ]:
bool(-15884)

True

In [ ]:
a='I am a data scientist'
a[-9:-3]

'scient'

In [ ]:
#len of string
len(a)

21

In [ ]:
#for replace
a.replace("s","T")

'I am a data TcientiTt'

In [ ]:
#create list of string
a.split()

['I', 'am', 'a', 'data', 'scientist']

In [ ]:
a.lower()

'i am a data scientist'

In [ ]:
a.upper()

'I AM A DATA SCIENTIST'

In [ ]:
a.title() #make 1st letter capital

'I Am A Data Scientist'

In [ ]:
a[:5] #return 1st five characters

'I am '

# List

In [ ]:
bikes=['trek','redline','giant']

In [ ]:
#get 1st item
bikes[0]

'trek'

In [ ]:
#last item
bikes[-1]

'giant'

In [ ]:
for i in bikes:
    print(i)

trek
redline
giant


In [ ]:
bikes=['trek','redline','giant']
bikes.append('splendor')
print(bikes)

['trek', 'redline', 'giant', 'splendor']


In [ ]:
cubes=[]

for i in range(0,11):
    cubes.append(i**3)
print(cubes)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [ ]:
cubes=[]

for i in range(0,11):
    cubes.append(i+1)
    print(cubes)

[1]
[1, 2]
[1, 2, 3]
[1, 2, 3, 4]
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [ ]:
cubes=0

for i in range(0,11):
    cubes=(i+1)
    print(cubes)

In [ ]:
#list comprehension
cubes=[i**3 for i in range(0,11)]
print(cubes)


[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]


In [ ]:
cubes
cubes[:2]  #slicing of list 

[0, 1]

In [ ]:
cubes[0]   #returning 1st value of list

0

In [ ]:
list=[1,5,1,4,7,8,9,6,1,12]
list

[1, 5, 1, 4, 7, 8, 9, 6, 1, 12]

In [ ]:
l=[1,5,1,4,7,8,9,6,1,12] #for sum of list element
s=sum(l)
print(s)

TypeError: 'int' object is not callable

In [ ]:
min(l)

1

In [ ]:
l.append(500) #append the value in list
l

[1, 5, 1, 4, 7, 8, 9, 6, 1, 12, 500, 500, 500]

In [ ]:
l.sort() #sort ascending
l

[1, 1, 1, 4, 5, 6, 7, 8, 9, 12, 500, 500, 500]

In [ ]:
l.sort(reverse=True) #sort descending
l

[500, 500, 500, 12, 9, 8, 7, 6, 5, 4, 1, 1, 1]

In [ ]:
bikes=['trek','redline','giant'] #convert list into string
" ".join(['A','B','C','D'])

'A B C D'

In [ ]:
l.reverse() #reverse the list
l

[500, 500, 500, 12, 9, 8, 7, 6, 5, 4, 1, 1, 1]

In [ ]:
l[-5:-3]

[5, 4]

# Tuples

In [ ]:
tuple='ranjit','ramesh','ghadge'
print(tuple)

('ranjit', 'ramesh', 'ghadge')


In [ ]:
#concanetate two tuples
tuple='ranjit','ramesh','ghadge'
tuple2= '25','360','23'
con=(tuple+tuple2)
con

('ranjit', 'ramesh', 'ghadge', '25', '360', '23')

In [ ]:
#slicing of tuple
a=(1,2,4,5,6,7,8,1,0,2,4)
print(a[2:8])

(4, 5, 6, 7, 8, 1)


In [ ]:
a[3:8]

(5, 6, 7, 8, 1)

# Dictionaries

In [ ]:
num={'one':1,'two':2,'three':3}
for word,num in num.items():
    if num%2==0:
        print(num)

2


In [ ]:
num={'one':1,'two':2,'three':3}
for n in num.values():
    print(n)

1
2
3


In [ ]:
num={'one':1,'two':2,'three':3}
for n in num.keys():
    print(n)

one
two
three


In [ ]:
num.values()

dict_values([1, 2, 3])

In [ ]:
num.keys()

dict_keys(['one', 'two', 'three'])

In [ ]:
num.items()

dict_items([('one', 1), ('two', 2), ('three', 3)])

In [ ]:
a=[a,b,v,d,f,g]
first=[a[0] for letter in a]
first

NameError: name 'b' is not defined

In [ ]:
a=['ranjit','ghadge','ramesh']
first=[letter[0] for letter in a]
first

['r', 'g', 'r']

In [ ]:
B=[2,4,6,7,8,2,4,9,7,15,20,3,6]
b=[i**2 for i in B if i%2==0]
b

[4, 16, 36, 64, 4, 16, 400, 36]

In [ ]:
list = ["a", "b", "c", "d"]
a = list[0:]
print(a)

c


In [ ]:

sq = [0, 1, 4, 9, 16, 25, 36, 49, 64]

print(sq[4:])



[16, 25, 36, 49, 64]


In [ ]:
string=input()
a=string[1:-1]
print(a)


names
ame


In [ ]:
list = [1, 1, 2, 3, 5, 8, 13]

print(list[list[4]])

8


In [ ]:
for i in range(10):

  if not i % 2 == 0:

    print(i+1)

2
4
6
8
10


In [ ]:
x = input()
print(x[0:3])

ranjit
ran


In [ ]:
N = int(input())

sum = 0
for i in range(1, N+1):
    sum += i
    print(sum)

In [ ]:
N = int(input())

sum = 0
for i in range(1, N+1):
    sum += i
    print(sum)

5
1
3
6
10
15


In [ ]:
x ="abc"

x *= 2

print(len(x))


6


In [ ]:
x = [2, 4, 5, 7, 4]

y = x.index(4)

print(y)

1


In [ ]:
nums = [1, 3, 5, 2, 4]

res = min(nums) + max(nums)

print(res)



6


In [ ]:
queue = ['John', 'Amy', 'Bob', 'Adam']

imp= input()

queue.append(imp)

print(queue)

wwww
['John', 'Amy', 'Bob', 'Adam', 'wwww']


In [ ]:
nums = [2,4,8,9,5]


nums.insert(1, 3)

nums.remove(9)

nums.insert(0, nums.count(8))

print(nums[3])

4


In [ ]:
nums = [2,4,8,9,5]


nums.insert(1, 3)

nums.remove(9)

nums.insert(0, nums.count(8))

print(nums[3])

4


In [ ]:
nums = [2,4,8,9,5]


nums.insert(1, 3)

print(nums)

[2, 3, 4, 8, 9, 5]


In [ ]:
nums = [4, 5, 7]
msg = "Numbers: {0} {1} {2}". format(nums[0], nums[1], nums[2])
print(msg)

Numbers: 4 5 7


In [ ]:
print("{0}{1}{0}".format("abra", "cad"))

abracadabra


In [ ]:
str="{c}, {b}, {a}".format(a=5, b=9, c=7)

print(str)

7, 9, 5


In [ ]:
x='hello'
words = x.split(' ')
res = words[0]
print(res)

hello


# List Comprehension:

Provide a concice way to create a list it consist bracket containing expression follow by for clouse then, zero or mmore for or if clauses this expression can be anything you can put all kinds of object in list.

In [ ]:
def sqr(nums):
  l=[]
  for i in nums:
    l.append(i*i)
  return l

nums=[1,2,4,5,6]
print(sqr(nums))

[1, 4, 16, 25, 36]


In [ ]:
list1=[i*i for i in nums]
print(list1)

[1, 4, 16, 25, 36]


In [ ]:
#If need even nos square
list1=[i*i for i in nums if i%2==0 ]
print(list1)

[4, 16, 36]


# Pandas

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Emily', 'Frank', 'George', 'Helen', 'Irene', 'Jack'],
    'Age': [25, 32, 18, 47, 29, 36, 21, 45, 28, 33],
    'Gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Male', 'Female', 'Female', 'Male'],
    'Country': ['USA', 'Canada', 'USA', 'Australia', 'UK', 'Canada', 'USA', 'Australia', 'UK', 'USA'],
    'Salary': [50000, 75000, 40000, 90000, 60000, 80000, 55000, 100000, 65000, 70000],
    'Department': ['Marketing', 'Finance', 'Marketing', 'IT', 'IT', 'HR', 'Marketing', 'IT', 'HR', 'Finance'],
    'Years of Experience': [3, 8, 1, 18, 6, 10, 2, 22, 5, 7],
    'Education Level': ['Bachelor', 'Master', 'High School', 'PhD', 'Bachelor', 'Master', 'Bachelor', 'PhD', 'Bachelor', 'Master']
}

df = pd.DataFrame(data)
print(df)


      Name  Age  Gender    Country  Salary Department  Years of Experience  \
0    Alice   25  Female        USA   50000  Marketing                    3   
1      Bob   32    Male     Canada   75000    Finance                    8   
2  Charlie   18    Male        USA   40000  Marketing                    1   
3    David   47    Male  Australia   90000         IT                   18   
4    Emily   29  Female         UK   60000         IT                    6   
5    Frank   36    Male     Canada   80000         HR                   10   
6   George   21    Male        USA   55000  Marketing                    2   
7    Helen   45  Female  Australia  100000         IT                   22   
8    Irene   28  Female         UK   65000         HR                    5   
9     Jack   33    Male        USA   70000    Finance                    7   

  Education Level  
0        Bachelor  
1          Master  
2     High School  
3             PhD  
4        Bachelor  
5          Master  
6

In [ ]:
#For checking a data type
df.dtypes

Name                   object
Age                     int64
Gender                 object
Country                object
Salary                  int64
Department             object
Years of Experience     int64
Education Level        object
dtype: object

In [ ]:
df.head()

Name  Age  Gender    Country  Salary Department  Years of Experience  \
0    Alice   25  Female        USA   50000  Marketing                    3   
1      Bob   32    Male     Canada   75000    Finance                    8   
2  Charlie   18    Male        USA   40000  Marketing                    1   
3    David   47    Male  Australia   90000         IT                   18   
4    Emily   29  Female         UK   60000         IT                    6   

  Education Level  
0        Bachelor  
1          Master  
2     High School  
3             PhD  
4        Bachelor

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Name                 10 non-null     object
 1   Age                  10 non-null     int64 
 2   Gender               10 non-null     object
 3   Country              10 non-null     object
 4   Salary               10 non-null     int64 
 5   Department           10 non-null     object
 6   Years of Experience  10 non-null     int64 
 7   Education Level      10 non-null     object
dtypes: int64(3), object(5)
memory usage: 768.0+ bytes


In [ ]:
#overall discriptive summary of dataframe

df.describe()

Age         Salary  Years of Experience
count  10.000000      10.000000            10.000000
mean   31.400000   68500.000000             8.200000
std     9.418658   18416.478129             6.860515
min    18.000000   40000.000000             1.000000
25%    25.750000   56250.000000             3.500000
50%    30.500000   67500.000000             6.500000
75%    35.250000   78750.000000             9.500000
max    47.000000  100000.000000            22.000000

In [ ]:
df.shape #for no of rows & columns

(10, 8)

In [ ]:
df.value_counts() #view unique values & counts

Name     Age  Gender  Country    Salary  Department  Years of Experience  Education Level
Alice    25   Female  USA        50000   Marketing   3                    Bachelor           1
Bob      32   Male    Canada     75000   Finance     8                    Master             1
Charlie  18   Male    USA        40000   Marketing   1                    High School        1
David    47   Male    Australia  90000   IT          18                   PhD                1
Emily    29   Female  UK         60000   IT          6                    Bachelor           1
Frank    36   Male    Canada     80000   HR          10                   Master             1
George   21   Male    USA        55000   Marketing   2                    Bachelor           1
Helen    45   Female  Australia  100000  IT          22                   PhD                1
Irene    28   Female  UK         65000   HR          5                    Bachelor           1
Jack     33   Male    USA        70000   Finance     7 

In [ ]:
df.apply (pd.Series.value_counts) #view uniue values & counts for all columns

Name  Age  Gender  Country  Salary  Department  \
1             NaN  NaN     NaN      NaN     NaN         NaN   
2             NaN  NaN     NaN      NaN     NaN         NaN   
3             NaN  NaN     NaN      NaN     NaN         NaN   
5             NaN  NaN     NaN      NaN     NaN         NaN   
6             NaN  NaN     NaN      NaN     NaN         NaN   
7             NaN  NaN     NaN      NaN     NaN         NaN   
8             NaN  NaN     NaN      NaN     NaN         NaN   
10            NaN  NaN     NaN      NaN     NaN         NaN   
18            NaN  1.0     NaN      NaN     NaN         NaN   
21            NaN  1.0     NaN      NaN     NaN         NaN   
22            NaN  NaN     NaN      NaN     NaN         NaN   
25            NaN  1.0     NaN      NaN     NaN         NaN   
28            NaN  1.0     NaN      NaN     NaN         NaN   
29            NaN  1.0     NaN      NaN     NaN         NaN   
32            NaN  1.0     NaN      NaN     NaN         NaN   
33            NaN  1.0     NaN      NaN     NaN         NaN   
36            NaN  1.0     NaN      NaN     NaN         NaN   
45            NaN  1.0     NaN      NaN     NaN         NaN   
47            NaN  1.0     NaN      NaN     NaN         NaN   
40000         NaN  NaN     NaN      NaN     1.0         NaN   
50000         NaN  NaN     NaN      NaN     1.0         NaN   
55000         NaN  NaN     NaN      NaN     1.0         NaN   
60000         NaN  NaN     NaN      NaN     1.0         NaN   
65000         NaN  NaN     NaN      NaN     1.0         NaN   
70000         NaN  NaN     NaN      NaN     1.0         NaN   
75000         NaN  NaN     NaN      NaN     1.0         NaN   
80000         NaN  NaN     NaN      NaN     1.0         NaN   
90000         NaN  NaN     NaN      NaN     1.0         NaN   
100000        NaN  NaN     NaN      NaN     1.0         NaN   
Alice         1.0  NaN     NaN      NaN     NaN         NaN   
Australia     NaN  NaN     NaN      2.0     NaN         NaN   
Bachelor      NaN  NaN     NaN      NaN     NaN         NaN   
Bob           1.0  NaN     NaN      NaN     NaN         NaN   
Canada        NaN  NaN     NaN      2.0     NaN         NaN   
Charlie       1.0  NaN     NaN      NaN     NaN         NaN   
David         1.0  NaN     NaN      NaN     NaN         NaN   
Emily         1.0  NaN     NaN      NaN     NaN         NaN   
Female        NaN  NaN     4.0      NaN     NaN         NaN   
Finance       NaN  NaN     NaN      NaN     NaN         2.0   
Frank         1.0  NaN     NaN      NaN     NaN         NaN   
George        1.0  NaN     NaN      NaN     NaN         NaN   
HR            NaN  NaN     NaN      NaN     NaN         2.0   
Helen         1.0  NaN     NaN      NaN     NaN         NaN   
High School   NaN  NaN     NaN      NaN     NaN         NaN   
IT            NaN  NaN     NaN      NaN     NaN         3.0   
Irene         1.0  NaN     NaN      NaN     NaN         NaN   
Jack          1.0  NaN     NaN      NaN     NaN         NaN   
Male          NaN  NaN     6.0      NaN     NaN         NaN   
Marketing     NaN  NaN     NaN      NaN     NaN         3.0   
Master        NaN  NaN     NaN      NaN     NaN         NaN   
PhD           NaN  NaN     NaN      NaN     NaN         NaN   
UK            NaN  NaN     NaN      2.0     NaN         NaN   
USA           NaN  NaN     NaN      4.0     NaN         NaN   

             Years of Experience  Education Level  
1                            1.0              NaN  
2                            1.0              NaN  
3                            1.0              NaN  
5                            1.0              NaN  
6                            1.0              NaN  
7                            1.0              NaN  
8                            1.0              NaN  
10                           1.0              NaN  
18                           1.0              NaN  
21                           NaN              NaN  
22                           1.0      

In [ ]:
#Enter string in index
df.index=['1st','2nd','3rd','4th','5th','6th','7th','8th','9th','10th']
df

Name  Age  Gender    Country  Salary Department  Years of Experience  \
1st     Alice   25  Female        USA   50000  Marketing                    3   
2nd       Bob   32    Male     Canada   75000    Finance                    8   
3rd   Charlie   18    Male        USA   40000  Marketing                    1   
4th     David   47    Male  Australia   90000         IT                   18   
5th     Emily   29  Female         UK   60000         IT                    6   
6th     Frank   36    Male     Canada   80000         HR                   10   
7th    George   21    Male        USA   55000  Marketing                    2   
8th     Helen   45  Female  Australia  100000         IT                   22   
9th     Irene   28  Female         UK   65000         HR                    5   
10th     Jack   33    Male        USA   70000    Finance                    7   

     Education Level  
1st         Bachelor  
2nd           Master  
3rd      High School  
4th              PhD  
5th         Bachelor  
6th           Master  
7th         Bachelor  
8th              PhD  
9th         Bachelor  
10th          Master

In [ ]:
df.index

Index(['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'], dtype='object')

In [ ]:
df.columns

Index(['Name', 'Age', 'Gender', 'Country', 'Salary', 'Department',
       'Years of Experience', 'Education Level'],
      dtype='object')

In [ ]:
df['Age'] # return column with label col as series

1st     25
2nd     32
3rd     18
4th     47
5th     29
6th     36
7th     21
8th     45
9th     28
10th    33
Name: Age, dtype: int64

In [ ]:
df[['Age','Salary']] # return column with label col as dataframe

Age  Salary
1st    25   50000
2nd    32   75000
3rd    18   40000
4th    47   90000
5th    29   60000
6th    36   80000
7th    21   55000
8th    45  100000
9th    28   65000
10th   33   70000

In [ ]:
df.to_numpy()

array([['Alice', 25, 'Female', 'USA', 50000, 'Marketing', 3, 'Bachelor'],
       ['Bob', 32, 'Male', 'Canada', 75000, 'Finance', 8, 'Master'],
       ['Charlie', 18, 'Male', 'USA', 40000, 'Marketing', 1,
        'High School'],
       ['David', 47, 'Male', 'Australia', 90000, 'IT', 18, 'PhD'],
       ['Emily', 29, 'Female', 'UK', 60000, 'IT', 6, 'Bachelor'],
       ['Frank', 36, 'Male', 'Canada', 80000, 'HR', 10, 'Master'],
       ['George', 21, 'Male', 'USA', 55000, 'Marketing', 2, 'Bachelor'],
       ['Helen', 45, 'Female', 'Australia', 100000, 'IT', 22, 'PhD'],
       ['Irene', 28, 'Female', 'UK', 65000, 'HR', 5, 'Bachelor'],
       ['Jack', 33, 'Male', 'USA', 70000, 'Finance', 7, 'Master']],
      dtype=object)

In [ ]:
# Let us get a subset which consists of first 8 rows and first 4 columns
df.iloc[:,:]

Name  Age  Gender    Country  Salary Department  Years of Experience  \
1st     Alice   25  Female        USA   50000  Marketing                    3   
2nd       Bob   32    Male     Canada   75000    Finance                    8   
3rd   Charlie   18    Male        USA   40000  Marketing                    1   
4th     David   47    Male  Australia   90000         IT                   18   
5th     Emily   29  Female         UK   60000         IT                    6   
6th     Frank   36    Male     Canada   80000         HR                   10   
7th    George   21    Male        USA   55000  Marketing                    2   
8th     Helen   45  Female  Australia  100000         IT                   22   
9th     Irene   28  Female         UK   65000         HR                    5   
10th     Jack   33    Male        USA   70000    Finance                    7   

     Education Level  
1st         Bachelor  
2nd           Master  
3rd      High School  
4th              PhD  
5th         Bachelor  
6th           Master  
7th         Bachelor  
8th              PhD  
9th         Bachelor  
10th          Master

In [ ]:
df.sort_index(axis=0,ascending=True) #axis=0 column, axis=1 row

Name  Age  Gender    Country  Salary Department  Years of Experience  \
10th     Jack   33    Male        USA   70000    Finance                    7   
1st     Alice   25  Female        USA   50000  Marketing                    3   
2nd       Bob   32    Male     Canada   75000    Finance                    8   
3rd   Charlie   18    Male        USA   40000  Marketing                    1   
4th     David   47    Male  Australia   90000         IT                   18   
5th     Emily   29  Female         UK   60000         IT                    6   
6th     Frank   36    Male     Canada   80000         HR                   10   
7th    George   21    Male        USA   55000  Marketing                    2   
8th     Helen   45  Female  Australia  100000         IT                   22   
9th     Irene   28  Female         UK   65000         HR                    5   

     Education Level  
10th          Master  
1st         Bachelor  
2nd           Master  
3rd      High School  
4th              PhD  
5th         Bachelor  
6th           Master  
7th         Bachelor  
8th              PhD  
9th         Bachelor

iloc gets rows (or columns) at particular positions in the index (so it only takes integers).

loc gets rows (or columns) with particular labels from the index.

In [ ]:
df.loc[:,['Age','Gender']] #return all rows

Age  Gender
1st    25  Female
2nd    32    Male
3rd    18    Male
4th    47    Male
5th    29  Female
6th    36    Male
7th    21    Male
8th    45  Female
9th    28  Female
10th   33    Male

In [ ]:
df.loc[['1st','2nd'], :] #return all columns

Name  Age  Gender Country  Salary Department  Years of Experience  \
1st  Alice   25  Female     USA   50000  Marketing                    3   
2nd    Bob   32    Male  Canada   75000    Finance                    8   

    Education Level  
1st        Bachelor  
2nd          Master

In [ ]:
df.loc[:,:] #loc[rows,columns]

Name  Age  Gender    Country  Salary Department  Years of Experience  \
1st     Alice   25  Female        USA   50000  Marketing                    3   
2nd       Bob   32    Male     Canada   75000    Finance                    8   
3rd   Charlie   18    Male        USA   40000  Marketing                    1   
4th     David   47    Male  Australia   90000         IT                   18   
5th     Emily   29  Female         UK   60000         IT                    6   
6th     Frank   36    Male     Canada   80000         HR                   10   
7th    George   21    Male        USA   55000  Marketing                    2   
8th     Helen   45  Female  Australia  100000         IT                   22   
9th     Irene   28  Female         UK   65000         HR                    5   
10th     Jack   33    Male        USA   70000    Finance                    7   

     Education Level  
1st         Bachelor  
2nd           Master  
3rd      High School  
4th              PhD  
5th         Bachelor  
6th           Master  
7th         Bachelor  
8th              PhD  
9th         Bachelor  
10th          Master

In [ ]:
# Now let us subset our dataframe in which we want to have first 8 rows identified with their rows labels and some named columns
#df.loc[5:8,['Age','Country']]

In [ ]:
df.loc[:,['Country']]

Country
1st         USA
2nd      Canada
3rd         USA
4th   Australia
5th          UK
6th      Canada
7th         USA
8th   Australia
9th          UK
10th        USA

In [ ]:
df.iloc[0,0] #if work throgh index(integer based undexing)

'Alice'

In [ ]:
df[['Age','Country']]

Age    Country
1st    25        USA
2nd    32     Canada
3rd    18        USA
4th    47  Australia
5th    29         UK
6th    36     Canada
7th    21        USA
8th    45  Australia
9th    28         UK
10th   33        USA

Boolean Indexing

In [ ]:
df['Country']=='USA'

1st      True
2nd     False
3rd      True
4th     False
5th     False
6th     False
7th      True
8th     False
9th     False
10th     True
Name: Country, dtype: bool

In [ ]:
USA_WALE=df[df['Country']=='USA']
USA_WALE.head()

Name  Age  Gender Country  Salary Department  Years of Experience  \
1st     Alice   25  Female     USA   50000  Marketing                    3   
3rd   Charlie   18    Male     USA   40000  Marketing                    1   
7th    George   21    Male     USA   55000  Marketing                    2   
10th     Jack   33    Male     USA   70000    Finance                    7   

     Education Level  
1st         Bachelor  
3rd      High School  
7th         Bachelor  
10th          Master

In [ ]:
USA_WALE=df[df['Country'] !='USA']
USA_WALE.head()

Name  Age  Gender    Country  Salary Department  Years of Experience  \
2nd    Bob   32    Male     Canada   75000    Finance                    8   
4th  David   47    Male  Australia   90000         IT                   18   
5th  Emily   29  Female         UK   60000         IT                    6   
6th  Frank   36    Male     Canada   80000         HR                   10   
8th  Helen   45  Female  Australia  100000         IT                   22   

    Education Level  
2nd          Master  
4th             PhD  
5th        Bachelor  
6th          Master  
8th             PhD

In [ ]:
long_age= df[df['Age']>30]
long_age

Name  Age  Gender    Country  Salary Department  Years of Experience  \
2nd     Bob   32    Male     Canada   75000    Finance                    8   
4th   David   47    Male  Australia   90000         IT                   18   
6th   Frank   36    Male     Canada   80000         HR                   10   
8th   Helen   45  Female  Australia  100000         IT                   22   
10th   Jack   33    Male        USA   70000    Finance                    7   

     Education Level  
2nd           Master  
4th              PhD  
6th           Master  
8th              PhD  
10th          Master

In [ ]:
df['half_Age']= df['Age']*0.5

In [ ]:
df.head()

Name  Age  Gender    Country  Salary Department  Years of Experience  \
1st    Alice   25  Female        USA   50000  Marketing                    3   
2nd      Bob   32    Male     Canada   75000    Finance                    8   
3rd  Charlie   18    Male        USA   40000  Marketing                    1   
4th    David   47    Male  Australia   90000         IT                   18   
5th    Emily   29  Female         UK   60000         IT                    6   

    Education Level  half_Age  
1st        Bachelor      12.5  
2nd          Master      16.0  
3rd     High School       9.0  
4th             PhD      23.5  
5th        Bachelor      14.5

In [ ]:
df['Total_Income']=df['Salary']*df['Years of Experience']

In [ ]:
df.head()

Name  Age  Gender    Country  Salary Department  Years of Experience  \
1st    Alice   25  Female        USA   50000  Marketing                    3   
2nd      Bob   32    Male     Canada   75000    Finance                    8   
3rd  Charlie   18    Male        USA   40000  Marketing                    1   
4th    David   47    Male  Australia   90000         IT                   18   
5th    Emily   29  Female         UK   60000         IT                    6   

    Education Level  half_Age  Total_Income  
1st        Bachelor      12.5        150000  
2nd          Master      16.0        600000  
3rd     High School       9.0         40000  
4th             PhD      23.5       1620000  
5th        Bachelor      14.5        360000

In [ ]:
#Drop the column

df.drop(['half_Age'],axis = 1,inplace=True)

In [ ]:
df.head()

Name  Age  Gender    Country  Salary Department  Years of Experience  \
1st    Alice   25  Female        USA   50000  Marketing                    3   
2nd      Bob   32    Male     Canada   75000    Finance                    8   
3rd  Charlie   18    Male        USA   40000  Marketing                    1   
4th    David   47    Male  Australia   90000         IT                   18   
5th    Emily   29  Female         UK   60000         IT                    6   

    Education Level  Total_Income  
1st        Bachelor        150000  
2nd          Master        600000  
3rd     High School         40000  
4th             PhD       1620000  
5th        Bachelor        360000

In [ ]:
df.drop(['1st','2nd']) #to drop a row

Name  Age  Gender    Country  Salary Department  Years of Experience  \
3rd   Charlie   18    Male        USA   40000  Marketing                    1   
4th     David   47    Male  Australia   90000         IT                   18   
5th     Emily   29  Female         UK   60000         IT                    6   
6th     Frank   36    Male     Canada   80000         HR                   10   
7th    George   21    Male        USA   55000  Marketing                    2   
8th     Helen   45  Female  Australia  100000         IT                   22   
9th     Irene   28  Female         UK   65000         HR                    5   
10th     Jack   33    Male        USA   70000    Finance                    7   

     Education Level  Total_Income  
3rd      High School         40000  
4th              PhD       1620000  
5th         Bachelor        360000  
6th           Master        800000  
7th         Bachelor        110000  
8th              PhD       2200000  
9th         Bachelor        325000  
10th          Master        490000

In [ ]:
df.drop(['Age'],axis=1) #To drop a column

Name  Gender    Country  Salary Department  Years of Experience  \
1st     Alice  Female        USA   50000  Marketing                    3   
2nd       Bob    Male     Canada   75000    Finance                    8   
3rd   Charlie    Male        USA   40000  Marketing                    1   
4th     David    Male  Australia   90000         IT                   18   
5th     Emily  Female         UK   60000         IT                    6   
6th     Frank    Male     Canada   80000         HR                   10   
7th    George    Male        USA   55000  Marketing                    2   
8th     Helen  Female  Australia  100000         IT                   22   
9th     Irene  Female         UK   65000         HR                    5   
10th     Jack    Male        USA   70000    Finance                    7   

     Education Level  Total_Income  
1st         Bachelor        150000  
2nd           Master        600000  
3rd      High School         40000  
4th              PhD       1620000  
5th         Bachelor        360000  
6th           Master        800000  
7th         Bachelor        110000  
8th              PhD       2200000  
9th         Bachelor        325000  
10th          Master        490000

In [ ]:
# Find the sum of values in a column
df['Salary'].sum()

685000

In [ ]:
#set column as index column
df.set_index('Name', inplace=True)

In [ ]:
df.head()

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
Alice     25  Female        USA   50000  Marketing                    3   
Bob       32    Male     Canada   75000    Finance                    8   
Charlie   18    Male        USA   40000  Marketing                    1   
David     47    Male  Australia   90000         IT                   18   
Emily     29  Female         UK   60000         IT                    6   

        Education Level  Total_Income  
Name                                   
Alice          Bachelor        150000  
Bob              Master        600000  
Charlie     High School         40000  
David               PhD       1620000  
Emily          Bachelor        360000

In [ ]:
a=df[df['Age']==32]
a

Age Gender Country  Salary Department  Years of Experience  \
Name                                                               
Bob    32   Male  Canada   75000    Finance                    8   

     Education Level  Total_Income  
Name                                
Bob           Master        600000

apply() method applies a function to every row in a pandas dataframe

In [ ]:
#uppercase
def to_uppercase(column):
    return column.upper()

In [ ]:
df['Capital_Name']=df['Country'].apply(to_uppercase)

In [ ]:
df.head()

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
Alice     25  Female        USA   50000  Marketing                    3   
Bob       32    Male     Canada   75000    Finance                    8   
Charlie   18    Male        USA   40000  Marketing                    1   
David     47    Male  Australia   90000         IT                   18   
Emily     29  Female         UK   60000         IT                    6   

        Education Level  Total_Income Capital_Name  
Name                                                
Alice          Bachelor        150000          USA  
Bob              Master        600000       CANADA  
Charlie     High School         40000          USA  
David               PhD       1620000    AUSTRALIA  
Emily          Bachelor        360000           UK

We can also sort our dataframe by some column values in either an ascending or descending order

In [ ]:
# Sort values in descending order
df.sort_values('Age', ascending=False)

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
David     47    Male  Australia   90000         IT                   18   
Helen     45  Female  Australia  100000         IT                   22   
Frank     36    Male     Canada   80000         HR                   10   
Jack      33    Male        USA   70000    Finance                    7   
Bob       32    Male     Canada   75000    Finance                    8   
Emily     29  Female         UK   60000         IT                    6   
Irene     28  Female         UK   65000         HR                    5   
Alice     25  Female        USA   50000  Marketing                    3   
George    21    Male        USA   55000  Marketing                    2   
Charlie   18    Male        USA   40000  Marketing                    1   

        Education Level  Total_Income Capital_Name  
Name                                                
David               PhD       1620000    AUSTRALIA  
Helen               PhD       2200000    AUSTRALIA  
Frank            Master        800000       CANADA  
Jack             Master        490000          USA  
Bob              Master        600000       CANADA  
Emily          Bachelor        360000           UK  
Irene          Bachelor        325000           UK  
Alice          Bachelor        150000          USA  
George         Bachelor        110000          USA  
Charlie     High School         40000          USA

In [ ]:
# We can also sort by the combination of two columns
df.sort_values(['Age','Salary'], ascending=[False,True]).head()

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                    
David   47    Male  Australia   90000         IT                   18   
Helen   45  Female  Australia  100000         IT                   22   
Frank   36    Male     Canada   80000         HR                   10   
Jack    33    Male        USA   70000    Finance                    7   
Bob     32    Male     Canada   75000    Finance                    8   

      Education Level  Total_Income Capital_Name  
Name                                              
David             PhD       1620000    AUSTRALIA  
Helen             PhD       2200000    AUSTRALIA  
Frank          Master        800000       CANADA  
Jack           Master        490000          USA  
Bob            Master        600000       CANADA

In [ ]:
# Find the list of unique values in a column
list(df['Country'].unique())

In [ ]:
df['Country'].unique()

In [ ]:
#df.columns=['N','A','B','C','D','E','F','G','H'] #rename of column
df

In [ ]:
df.isnull() #checks for null values, return boolean array

Age  Gender  Country  Salary  Department  Years of Experience  \
Name                                                                       
Alice    False   False    False   False       False                False   
Bob      False   False    False   False       False                False   
Charlie  False   False    False   False       False                False   
David    False   False    False   False       False                False   
Emily    False   False    False   False       False                False   
Frank    False   False    False   False       False                False   
George   False   False    False   False       False                False   
Helen    False   False    False   False       False                False   
Irene    False   False    False   False       False                False   
Jack     False   False    False   False       False                False   

         Education Level  Total_Income  Capital_Name  
Name                                                  
Alice              False         False         False  
Bob                False         False         False  
Charlie            False         False         False  
David              False         False         False  
Emily              False         False         False  
Frank              False         False         False  
George             False         False         False  
Helen              False         False         False  
Irene              False         False         False  
Jack               False         False         False

In [ ]:
df.notnull() #opposite to isnull

Age  Gender  Country  Salary  Department  Years of Experience  \
Name                                                                      
Alice    True    True     True    True        True                 True   
Bob      True    True     True    True        True                 True   
Charlie  True    True     True    True        True                 True   
David    True    True     True    True        True                 True   
Emily    True    True     True    True        True                 True   
Frank    True    True     True    True        True                 True   
George   True    True     True    True        True                 True   
Helen    True    True     True    True        True                 True   
Irene    True    True     True    True        True                 True   
Jack     True    True     True    True        True                 True   

         Education Level  Total_Income  Capital_Name  
Name                                                  
Alice               True          True          True  
Bob                 True          True          True  
Charlie             True          True          True  
David               True          True          True  
Emily               True          True          True  
Frank               True          True          True  
George              True          True          True  
Helen               True          True          True  
Irene               True          True          True  
Jack                True          True          True

In [ ]:
df.dropna() #drop all rows contain null values

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
Alice     25  Female        USA   50000  Marketing                    3   
Bob       32    Male     Canada   75000    Finance                    8   
Charlie   18    Male        USA   40000  Marketing                    1   
David     47    Male  Australia   90000         IT                   18   
Emily     29  Female         UK   60000         IT                    6   
Frank     36    Male     Canada   80000         HR                   10   
George    21    Male        USA   55000  Marketing                    2   
Helen     45  Female  Australia  100000         IT                   22   
Irene     28  Female         UK   65000         HR                    5   
Jack      33    Male        USA   70000    Finance                    7   

        Education Level  Total_Income Capital_Name  
Name                                                
Alice          Bachelor        150000          USA  
Bob              Master        600000       CANADA  
Charlie     High School         40000          USA  
David               PhD       1620000    AUSTRALIA  
Emily          Bachelor        360000           UK  
Frank            Master        800000       CANADA  
George         Bachelor        110000          USA  
Helen               PhD       2200000    AUSTRALIA  
Irene          Bachelor        325000           UK  
Jack             Master        490000          USA

In [ ]:
df.dropna(axis=1) #drop all columns contain null values

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
Alice     25  Female        USA   50000  Marketing                    3   
Bob       32    Male     Canada   75000    Finance                    8   
Charlie   18    Male        USA   40000  Marketing                    1   
David     47    Male  Australia   90000         IT                   18   
Emily     29  Female         UK   60000         IT                    6   
Frank     36    Male     Canada   80000         HR                   10   
George    21    Male        USA   55000  Marketing                    2   
Helen     45  Female  Australia  100000         IT                   22   
Irene     28  Female         UK   65000         HR                    5   
Jack      33    Male        USA   70000    Finance                    7   

        Education Level  Total_Income Capital_Name  
Name                                                
Alice          Bachelor        150000          USA  
Bob              Master        600000       CANADA  
Charlie     High School         40000          USA  
David               PhD       1620000    AUSTRALIA  
Emily          Bachelor        360000           UK  
Frank            Master        800000       CANADA  
George         Bachelor        110000          USA  
Helen               PhD       2200000    AUSTRALIA  
Irene          Bachelor        325000           UK  
Jack             Master        490000          USA

In [ ]:
df.dropna(axis=1,thresh=1) #drop all columns contain null values less than n

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
Alice     25  Female        USA   50000  Marketing                    3   
Bob       32    Male     Canada   75000    Finance                    8   
Charlie   18    Male        USA   40000  Marketing                    1   
David     47    Male  Australia   90000         IT                   18   
Emily     29  Female         UK   60000         IT                    6   
Frank     36    Male     Canada   80000         HR                   10   
George    21    Male        USA   55000  Marketing                    2   
Helen     45  Female  Australia  100000         IT                   22   
Irene     28  Female         UK   65000         HR                    5   
Jack      33    Male        USA   70000    Finance                    7   

        Education Level  Total_Income Capital_Name  
Name                                                
Alice          Bachelor        150000          USA  
Bob              Master        600000       CANADA  
Charlie     High School         40000          USA  
David               PhD       1620000    AUSTRALIA  
Emily          Bachelor        360000           UK  
Frank            Master        800000       CANADA  
George         Bachelor        110000          USA  
Helen               PhD       2200000    AUSTRALIA  
Irene          Bachelor        325000           UK  
Jack             Master        490000          USA

In [ ]:
df.fillna(df.mean()) #replace all null values with mean

C:\Users\RANJIT\AppData\Local\Temp\ipykernel_132488\234936199.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean()) #replace all null values with mean


Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
Alice     25  Female        USA   50000  Marketing                    3   
Bob       32    Male     Canada   75000    Finance                    8   
Charlie   18    Male        USA   40000  Marketing                    1   
David     47    Male  Australia   90000         IT                   18   
Emily     29  Female         UK   60000         IT                    6   
Frank     36    Male     Canada   80000         HR                   10   
George    21    Male        USA   55000  Marketing                    2   
Helen     45  Female  Australia  100000         IT                   22   
Irene     28  Female         UK   65000         HR                    5   
Jack      33    Male        USA   70000    Finance                    7   

        Education Level  Total_Income Capital_Name  
Name                                                
Alice          Bachelor        150000          USA  
Bob              Master        600000       CANADA  
Charlie     High School         40000          USA  
David               PhD       1620000    AUSTRALIA  
Emily          Bachelor        360000           UK  
Frank            Master        800000       CANADA  
George         Bachelor        110000          USA  
Helen               PhD       2200000    AUSTRALIA  
Irene          Bachelor        325000           UK  
Jack             Master        490000          USA

In [ ]:
#df.astype(float) #Convert datatype of series to float

In [ ]:
df.replace(1,'one') #replace all values equal to 1 with one

Age  Gender    Country  Salary Department Years of Experience  \
Name                                                                     
Alice     25  Female        USA   50000  Marketing                   3   
Bob       32    Male     Canada   75000    Finance                   8   
Charlie   18    Male        USA   40000  Marketing                 one   
David     47    Male  Australia   90000         IT                  18   
Emily     29  Female         UK   60000         IT                   6   
Frank     36    Male     Canada   80000         HR                  10   
George    21    Male        USA   55000  Marketing                   2   
Helen     45  Female  Australia  100000         IT                  22   
Irene     28  Female         UK   65000         HR                   5   
Jack      33    Male        USA   70000    Finance                   7   

        Education Level  Total_Income Capital_Name  
Name                                                
Alice          Bachelor        150000          USA  
Bob              Master        600000       CANADA  
Charlie     High School         40000          USA  
David               PhD       1620000    AUSTRALIA  
Emily          Bachelor        360000           UK  
Frank            Master        800000       CANADA  
George         Bachelor        110000          USA  
Helen               PhD       2200000    AUSTRALIA  
Irene          Bachelor        325000           UK  
Jack             Master        490000          USA

In [ ]:
df.rename(columns={'N':'New Age'}) #rename of selected column

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                      
Alice     25  Female        USA   50000  Marketing                    3   
Bob       32    Male     Canada   75000    Finance                    8   
Charlie   18    Male        USA   40000  Marketing                    1   
David     47    Male  Australia   90000         IT                   18   
Emily     29  Female         UK   60000         IT                    6   
Frank     36    Male     Canada   80000         HR                   10   
George    21    Male        USA   55000  Marketing                    2   
Helen     45  Female  Australia  100000         IT                   22   
Irene     28  Female         UK   65000         HR                    5   
Jack      33    Male        USA   70000    Finance                    7   

        Education Level  Total_Income Capital_Name  
Name                                                
Alice          Bachelor        150000          USA  
Bob              Master        600000       CANADA  
Charlie     High School         40000          USA  
David               PhD       1620000    AUSTRALIA  
Emily          Bachelor        360000           UK  
Frank            Master        800000       CANADA  
George         Bachelor        110000          USA  
Helen               PhD       2200000    AUSTRALIA  
Irene          Bachelor        325000           UK  
Jack             Master        490000          USA

In [ ]:
df1.append(df2)  #add rows in end of df1 to the df2, column should be identical

NameError: name 'df1' is not defined

In [ ]:
pd.concat([df1,df2],axis=1) #add rows in end of df1 to the df2, rows should be identical

NameError: name 'df1' is not defined

**FILTER, SORT & GROUPBY **


In [ ]:
df

In [ ]:
df[df['Age']>20] #rows where age greater than 20

Age  Gender    Country  Salary Department  Years of Experience  \
Name                                                                     
Alice    25  Female        USA   50000  Marketing                    3   
Bob      32    Male     Canada   75000    Finance                    8   
David    47    Male  Australia   90000         IT                   18   
Emily    29  Female         UK   60000         IT                    6   
Frank    36    Male     Canada   80000         HR                   10   
George   21    Male        USA   55000  Marketing                    2   
Helen    45  Female  Australia  100000         IT                   22   
Irene    28  Female         UK   65000         HR                    5   
Jack     33    Male        USA   70000    Finance                    7   

       Education Level  Total_Income Capital_Name  
Name                                               
Alice         Bachelor        150000          USA  
Bob             Master        600000       CANADA  
David              PhD       1620000    AUSTRALIA  
Emily         Bachelor        360000           UK  
Frank           Master        800000       CANADA  
George        Bachelor        110000          USA  
Helen              PhD       2200000    AUSTRALIA  
Irene         Bachelor        325000           UK  
Jack            Master        490000          USA

In [ ]:
df[(df['Age']>20) & (df['Age']<30)] #between

In [ ]:
df.sort_values('Age') #sort values also add ascending

In [ ]:
df.groupby('Gender') #create groupby object for values 

In [ ]:
df.groupby('Gender'),['Country'] #for multiple

Statistical

In [ ]:
df.describe()

In [ ]:
df.mean()

In [ ]:
df.corr()

In [ ]:
df.count()

In [ ]:
df.max()

In [ ]:
df.min()

In [ ]:
df.median()

In [ ]:
df.std()

# Numpy

In [2]:
import numpy as np

In [ ]:
#create array from list- 1D Prime no array
prime_array=np.array([2,3,5,7,11])
print(prime_array)

[ 2  3  5  7 11]


In [ ]:
#check data type of prime_array
type(prime_array)

numpy.ndarray

In [ ]:
#2D array
two_D = np.array([[1,2,3],[4,5,6]])
print(two_D)

[[1 2 3]
 [4 5 6]]


In [ ]:
two_D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
two_D.shape

(2, 3)

In [ ]:
#create 3D array
three_D = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(three_D)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
three_D.shape

(1, 3, 3)

Array Inspection

In [ ]:
three_D

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
#ndarray.shape
three_D.shape     #(no of array, row, column)
                  #(diamensions-1,nos,innernos)

(1, 3, 3)

In [ ]:
two_D.shape

(2, 3)

In [ ]:
#ndarray.ndin -- returns no of array dimensions
three_D.ndim

3

In [ ]:
two_D.ndim

2

In [ ]:
#ndarray.size -- total no of elements in array
three_D.size


9

In [ ]:
two_D.size

6

In [ ]:
#ndarray.dtype---check data type of array
three_D.dtype


dtype('int64')

In [ ]:
two_D.dtype

dtype('int64')

In [ ]:
#ndarray.astype----To change data type of array
three_D=three_D.astype('float')

three_D.dtype


dtype('float64')

Different Way of Creating Array

In [4]:
#Array with specified shape
uninitialized_array= np.empty([5,3],dtype=int)
print(uninitialized_array)

[[           45096208                   0 8511838618078834295]
 [2322280074044863337 2314885437609439074 4211540083635878432]
 [ 723518651976410656 8030881587503916371 3255307777713450250]
 [7219961191666813485 7595356248831179296 2336630925664679027]
 [8459851789882320242 8317701431971963244                 288]]


In [6]:
#initializing with zeros
zeros_array = np.zeros((5,3)) #default data type float
other_zero_array = np.zeros((4,3),dtype = int)
print(zeros_array)
print(other_zero_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
#initializing with zeros
ones_array = np.ones((5,3)) #default data type float
other_ones_array = np.ones((4,3),dtype = int)
print(ones_array)
print(other_ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


Array with range

In [12]:
A = np.arange(10)
print(A)

[0 1 2 3 4 5 6 7 8 9]


In [14]:
B = np.arange(1,20,2) #(start,stop,step,dtpe)
B

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [19]:
# to get values in even space

A = np.linspace(10,20,9 , endpoint = False, retstep = True)
A

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889]),
 1.1111111111111112)

Array from random Nums

In [20]:
A = np.random.random((4,5))
print(A)

[[0.21575855 0.58871088 0.12215181 0.2311553  0.44333959]
 [0.77201966 0.36081836 0.25494115 0.31698995 0.29790039]
 [0.99565968 0.92794438 0.99835657 0.13148876 0.99844739]
 [0.53516909 0.88747093 0.174304   0.43060917 0.99680686]]


In [22]:
B = np.random.randint(0,5,size=(2,3,4))
print(B)

[[[2 0 2 0]
  [0 0 3 4]
  [1 0 2 1]]

 [[1 0 1 4]
  [2 3 4 0]
  [4 2 0 1]]]


Array with specified num

In [25]:
a = np.full((3,3),30)   #---np.full(shape,value)
print(a)

[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [24]:
a = np.ones((3,3))*30
print(a)

[[30. 30. 30.]
 [30. 30. 30.]
 [30. 30. 30.]]


In [27]:
#identity matrix

A = np.identity(3)
print(A)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create Array from existing data.

In [29]:
# Convert list to array

list1 = [1,2,3,4,5]
array_for_list = np.asarray(list1)
list1

[1, 2, 3, 4, 5]

In [30]:
tuple1 = (1,2,3,4)
array_for_tuple = np.asarray(tuple1)
tuple1

(1, 2, 3, 4)

Indexing & Slicing

In [36]:
a = np.arange(10)
print(a)
print(a[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [37]:
a[2:8]

array([2, 3, 4, 5, 6, 7])

In [40]:
a =np.random.random(10)
print(a)
print(a[::2])

[0.3976136  0.17735659 0.53883925 0.53578592 0.28938613 0.4753272
 0.60495408 0.12719803 0.34831614 0.00192775]
[0.3976136  0.53883925 0.28938613 0.60495408 0.34831614]


In [41]:
# when certain parameters are unspecified
a = np.arange(10)
print(a[:6:2]) # starting index is unspecified (default = 0)
print(a[1::2]) # ending index is unspecified (default = array size)
print(a[1:6:]) # steps is unspecified (default = 1)

[0 2 4]
[1 3 5 7 9]
[1 2 3 4 5]


Slicing- 2D Array

In [42]:
a = np.array([[1,2,3],[4,5,6]])  # 0,1st row & 0,1,2nd column
print(a)
print(a[1,2])

[[1 2 3]
 [4 5 6]]
6


In [43]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[0:2]) 
print(a[0:2,-2:]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]


In [45]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
#getting 1st row
print(a[0:1,:])

[[1 2 3]]


In [49]:
#getting 1st column
print(a[:,0:1])


[[1]
 [4]
 [7]]


Slicing 3D Array

In [50]:
# For 3-D array slicing the format is array[index,row,column]
a = np.array([[[1,2],[3,4],[5,6]],
             [[7,8],[9,10],[11,12]],
             [[13,14],[15,16],[17,18]]])
print(a)
print(a[0:2])
# print(a[0:2,1:])
print(a[0:2,1:,1:])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 4]
  [ 6]]

 [[10]
  [12]]]


Array Manipulation

In [54]:
A = np.array(np.random.randint(10,45,(8,2))) #randint take size random not, randint take two nos random take 2
print(A)
print(A.shape)

[[31 15]
 [36 34]
 [33 13]
 [39 44]
 [14 41]
 [18 15]
 [41 42]
 [19 22]]
(8, 2)


In [55]:
tranA= np.transpose(A)
print(tranA)

[[31 36 33 39 14 18 41 19]
 [15 34 13 44 41 15 42 22]]


In [59]:
#np.reshape
A = np.array(np.random.randint(10,45,(3,8))) # 2D
print(A)

newshape=(2,6,2)
new_shape = np.reshape(A,newshape)
print(new_shape)   #multiplication should be same of elements

[[21 11 14 36 22 32 18 23]
 [28 27 12 27 17 19 10 11]
 [26 19 28 32 37 38 38 42]]
[[[21 11]
  [14 36]
  [22 32]
  [18 23]
  [28 27]
  [12 27]]

 [[17 19]
  [10 11]
  [26 19]
  [28 32]
  [37 38]
  [38 42]]]


In [60]:
# Lets take an example of a list
a = [1,2,3]
b = a
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[10, 2, 3]


In [61]:
# Lets use the copy method
a = [1,2,3]
b = a.copy()
b[0] = 10
print(b)
print(a)

[10, 2, 3]
[1, 2, 3]


Basic operations & functions

In [63]:
#np.add()
np.arange(3)+5  #0+5,1+5,2+5


array([5, 6, 7])

In [64]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [65]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [66]:
#Example 2
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(1,10,(2,2))
print(b)

[[4 2 3 3]
 [4 5 4 2]]
[[1 1]
 [7 7]]


In [67]:
np.add(a,b)

ValueError: ignored

In [68]:
a=np.random.randint(2,6,(2,4))
print(a)
b=np.random.randint(0,5,(2,4))
print(b)

[[4 5 2 3]
 [2 4 4 3]]
[[4 0 4 3]
 [2 3 0 0]]


In [69]:
np.multiply(a,b)

array([[16,  0,  8,  9],
       [ 4, 12,  0,  0]])

In [70]:
a=np.random.randint(5,9,(2,4))
print(a)

[[6 8 5 5]
 [6 8 7 6]]


In [71]:
print(np.sum(a)) 
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))

51
[12 16 12 11]
[24 27]


In [ ]:
# Calculate minimum
print(np.min(a))
print(np.min(a,axis=2)) # Across Column

In [73]:
# Sort the array
a=np.random.randint(0,20,(3,3))
print(a)

[[18 18 11]
 [ 1 13  2]
 [19 10 12]]


In [74]:
print(np.sort(a,axis=0)) # Ascending

[[ 1 10  2]
 [18 13 11]
 [19 18 12]]


In [75]:
print(np.sort(a,axis=1))

[[11 18 18]
 [ 1  2 13]
 [10 12 19]]


In [76]:
print(-np.sort(-a,axis=1)) # Descending

[[18 18 11]
 [13  2  1]
 [19 12 10]]


In [77]:
sum(np.arange(3)*np.arange(3).transpose())

5

# Recursion

In [78]:
def multipy(a,b):

  result = 0

  for i in range(b):
    result = result + a

  print(result)

multipy(5,2)

10


In [79]:
#same code using recursion

def mul(a,b):
  if b == 1:
    return a
  else:
    return a+mul(a,b-1)
  
print(mul(5,2))

10


In [80]:
def fact(num):
  if num == 1:
    return 1
  else:
    #5=5*4
    return num*fact(num-1)
print(fact(5))


120


In [82]:
#Palindrome
def palin(text):
  if len(text) <= 1:
    print('palindrome')
  else:
    if text[0] == text[-1]:
      palin(text[1:-1])
    else:
      print('Not pali')


print(palin('madam'))

palindrome
None


In [85]:
#fibonacci

def fib(m):
  if m==0 or m==1:
    return 1
  else:
    return fib(m-1)+fib(m-2)
print(fib(12))

233


In [87]:
import time


def fib(m):
  if m==0 or m==1:
    return 1
  else:
    return fib(m-1)+fib(m-2)
print(fib(18))

start = time.time()
print(fib(5))

print(time.time()-start)

4181
8
0.00013780593872070312
